# -*- coding: utf-8 -*-
"""minio_manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m51p4OKSZWNsukV0vk2Pw_O27GKUTViF
"""

from io import BytesIO
from minio import Minio
from minio.error import S3Error
from src.common.minio_client import get_minio_client

# Localhost MinIO client
client = get_minio_client()

LANDING_BUCKET = "landing-zone"
FORMATTED_BUCKET = "formatted-zone"
TRUSTED_BUCKET = "trusted-zone"
REJECTED_BUCKET = "rejected-zone"


LANDING_FOLDERS = [
    "temporal_landing/",
    "persistent_landing/",
    "persistent_landing/image_data/",
    "persistent_landing/video_data/",
    "persistent_landing/text_data/",
]

FORMATTED_FOLDERS = [
    "formatted/",
    "formatted/image_data/",
    "formatted/video_data/",
    "formatted/text_data/",
]

TRUSTED_FOLDERS = [
    "trusted/",
    "trusted/image_data/",
    "trusted/video_data/",
    "trusted/text_data/",
]

REJECTED_FOLDERS = [
    "rejected/",
    "rejected/image_data/",
    "rejected/video_data/",
    "rejected/text_data/",
]

def create_bucket(bucket: str):
    if not client.bucket_exists(bucket):
        client.make_bucket(bucket)


def create_folder(bucket: str, folder: str):
    # Folders must end with "/"
    if not folder.endswith("/"):
        folder += "/"

    # The object we put inside the bucket is an empty folder
    client.put_object(
        bucket,
        folder,
        data=BytesIO(b""),
        length=0,
        content_type="application/octet-stream",
    )

def main():
    # Create landing bucket
    create_bucket(LANDING_BUCKET)
    for f in LANDING_FOLDERS:
        create_folder(LANDING_BUCKET, f)
        print(f"[OK]: {LANDING_BUCKET}/{f}")

    # Create formatted bucket
    create_bucket(FORMATTED_BUCKET)
    for f in FORMATTED_FOLDERS:
        create_folder(FORMATTED_BUCKET, f)
        print(f"[OK]: {FORMATTED_BUCKET}/{f}")

    # Create trusted bucket
    create_bucket(TRUSTED_BUCKET)
    for f in TRUSTED_FOLDERS:
        create_folder(TRUSTED_BUCKET, f)
        print(f"[OK]: {TRUSTED_BUCKET}/{f}")

    # Create rejected bucket
    create_bucket(REJECTED_BUCKET)
    for f in REJECTED_FOLDERS:
        create_folder(REJECTED_BUCKET, f)
        print(f"[OK]: {REJECTED_BUCKET}/{f}")

if __name__ == "__main__":
    try:
        main()
    except S3Error as e:
        print(f"Error MinIO: {e}")